### ISSUE TITLE
Configuration du plugin

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/renamer#5]
A l'installation du plugin, sa configuration est vide, càd qu'aucune langue n'a encore été sélectionnée.
Si l'on va dans Admin > Renamer -> erreur php à l'écran et dans php-errors.log
  *** PHP Warning(2): Invalid argument supplied for foreach() 
  Backtrace : 
  plugins/renamer/inc/config.class.php:122
  plugins/renamer/inc/renamer.class.php:78           PluginRenamerConfig->getelectedLanguage() 
  plugins/renamer/inc/renamer.class.php:57           PluginRenamerRenamer->showFormToOverload() 
  plugins/renamer/front/renamer.form.php:62          PluginRenamerRenamer->showForm() 

De même, impossible de supprimer la dernière des langues sélectionnées -> erreur php
  *** PHP Notice(8): Undefined index: pick_list_lang
  Backtrace :
  plugins/renamer/front/config.form.php:56

**Comment by flegastelois** [comment]
Salut Benoît,

Tu constates cela sur quelle version du plugin ?

Bien à toi,
François.

**Comment by blerohellec** [comment]
0.85-1.0.
Désolé de ne pas l'avoir précisé.

**Comment by blerohellec** [comment]
Perfect

**Comment by blerohellec** [comment]
J'ai parlé trop vite : le 2ème point n'est pas encore corrigé.
Dans la config du plugin (Config > Plugins > Renamer), supprimer la dernière (ou toutes) des langues du tableau de droite, puis Modifier, génère l'erreur PHP citée. Et le résultat n'est pas sauvegardé.

**Comment by blerohellec** [comment]
OK. C'est bon
